### ISSUE TITLE
Investigate directories not getting created in production

### ISSUE THREAD

**Issue by maxsibilla** [sennetconsortium/ingest-api#144]
A user from "TMC - The Jackson Laboratory" has reported a hangup during the bulk registration process of "Sections" and "Datasets". During both processes the entities do get created, however, with Datasets the directories never get created on the file system.

Potentially relevant log:
```
[2023-09-25 12:35:23] INFO in basic: Setting up a BasicAuthorizer. It will use an auth type of Basic and cannot handle 401s.
[2023-09-25 12:35:23] INFO in basic: BasicAuthorizer.username = c4018852-db38-4142-9e8c-fd5484806647
[2023-09-25 12:35:23] INFO in base: [instance:140201958453456] Creating client of type <class 'globus_sdk.auth.client_types.confidential_client.ConfidentialAppAuthClient'> for service "auth"
[2023-09-25 12:35:23] DEBUG in config: Service URL Lookup for "auth" under env "default"
[2023-09-25 12:35:23] DEBUG in config: Service URL Lookup Result: "auth" is at "https://auth.globus.org/"
[2023-09-25 12:35:23] DEBUG in config: Config lookup of [environment default]:http_timeout failed, checking [general] for a value as well
[2023-09-25 12:35:23] DEBUG in config: default http_timeout set to 60
[2023-09-25 12:35:23] INFO in confidential_client: [instance:140201958453456] Finished initializing client, client_id=c4018852-db38-4142-9e8c-fd5484806647
[2023-09-25 12:35:23] INFO in confidential_client: [instance:140201958453456] Starting OAuth2 Authorization Code Grant Flow
[2023-09-25 12:35:23] DEBUG in oauth2_authorization_code: Starting Authorization Code Flow with params:
[2023-09-25 12:35:23] DEBUG in oauth2_authorization_code: auth_client.client_id=c4018852-db38-4142-9e8c-fd5484806647
[2023-09-25 12:35:23] DEBUG in oauth2_authorization_code: redirect_uri=https://ingest.api.sennetconsortium.org/login
[2023-09-25 12:35:23] DEBUG in oauth2_authorization_code: refresh_tokens=True
[2023-09-25 12:35:23] DEBUG in oauth2_authorization_code: state=_default
[2023-09-25 12:35:23] DEBUG in oauth2_authorization_code: requested_scopes=openid profile email urn:globus:auth:scope:transfer.api.globus.org:all
[2023-09-25 12:35:23] DEBUG in oauth2_authorization_code: Building authorization URI. Base URL: https://auth.globus.org/v2/oauth2/authorize
[2023-09-25 12:35:23] DEBUG in oauth2_authorization_code: additional_params={'scope': 'openid profile email urn:globus:auth:scope:transfer.api.globus.org:all urn:globus:auth:scope:auth.globus.org:view_identities urn:globus:auth:scope:groups.api.globus.org:all'}
[2023-09-25 12:35:23] INFO in base: [instance:140201958453456] Got authorization URL: https://auth.globus.org/v2/oauth2/authorize?client_id=c4018852-db38-4142-9e8c-fd5484806647&redirect_uri=https%3A%2F%2Fingest.api.sennetconsortium.org%2Flogin&scope=openid+profile+email+urn%3Aglobus%3Aauth%3Ascope%3Atransfer.api.globus.org%3Aall+urn%3Aglobus%3Aauth%3Ascope%3Aauth.globus.org%3Aview_identities+urn%3Aglobus%3Aauth%3Ascope%3Agroups.api.globus.org%3Aall&state=_default&response_type=code&access_type=offline
[pid: 51|app: 0|req: 12635/14327] 172.31.51.117 () {62 vars in 2761 bytes} [Mon Sep 25 12:35:23 2023] GET /login => generated 1067 bytes in 1 msecs (HTTP/1.1 302) 3 headers in 516 bytes (1 switches on core 0)
```

**Comment by maxsibilla** [comment]
@libpitt was able to create 39 datasets using the bulk registration method without issue on production. Potentially a user-specific or group-specific issue?

**Comment by yuanzhou** [comment]
I did notice such errors from Friday 9/22 and today 9/25 that likely are related to the file directory creation:

```
[2023-09-25 15:36:44] DEBUG in connectionpool: https://entity.api.sennetconsortium.org:443 "POST /entities/dataset HTTP/1.1" 200 912
[2023-09-25 15:36:44] INFO in ingest_file_helper: Getting dataset directory absolute path ... protected, None 
[2023-09-25 15:36:44] ERROR in ingest_file_helper: join() argument must be str, bytes, or os.PathLike object, not 'NoneType'
Traceback (most recent call last):
  File "/usr/src/app/src/./routes/entity_CRUD/ingest_file_helper.py", line 103, in create_dataset_directory
    new_directory_path = self.get_dataset_directory_absolute_path(dataset_record, group_uuid, dataset_uuid)
  File "/usr/src/app/src/./routes/entity_CRUD/ingest_file_helper.py", line 43, in get_dataset_directory_absolute_path
    return self.__dataset_directory_absolute_path(access_level, group_uuid, dataset_uuid, published)
  File "/usr/src/app/src/./routes/entity_CRUD/ingest_file_helper.py", line 49, in __dataset_directory_absolute_path
    abs_path = str(os.path.join(base_dir, grp_name, dataset_uuid))
  File "/usr/lib64/python3.9/posixpath.py", line 90, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib64/python3.9/genericpath.py", line 152, in _check_arg_types
    raise TypeError(f'{funcname}() argument must be str, bytes, or '
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'NoneType'
```

```
[2023-09-25 15:37:05] INFO in ingest_file_helper: Getting dataset directory absolute path ... protected, None 
[2023-09-25 15:37:05] ERROR in ingest_file_helper: join() argument must be str, bytes, or os.PathLike object, not 'NoneType'
Traceback (most recent call last):
  File "/usr/src/app/src/./routes/entity_CRUD/ingest_file_helper.py", line 103, in create_dataset_directory
    new_directory_path = self.get_dataset_directory_absolute_path(dataset_record, group_uuid, dataset_uuid)
  File "/usr/src/app/src/./routes/entity_CRUD/ingest_file_helper.py", line 43, in get_dataset_directory_absolute_path
    return self.__dataset_directory_absolute_path(access_level, group_uuid, dataset_uuid, published)
  File "/usr/src/app/src/./routes/entity_CRUD/ingest_file_helper.py", line 49, in __dataset_directory_absolute_path
    abs_path = str(os.path.join(base_dir, grp_name, dataset_uuid))
  File "/usr/lib64/python3.9/posixpath.py", line 90, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib64/python3.9/genericpath.py", line 152, in _check_arg_types
    raise TypeError(f'{funcname}() argument must be str, bytes, or '
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'NoneType'
```

```
[2023-09-25 18:09:22] ERROR in app: Exception on /privs/0ebc13fb-ee72-11ec-87fd-31892bd489e1/has-write [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/src/app/src/./routes/privs/__init__.py", line 41, in privs_has_write_on_group_uuid
    has_write_privs: bool = auth_helper_instance.check_write_privs(groups_token, group_uuid)
  File "/usr/local/lib/python3.9/site-packages/hubmap_commons/hm_auth.py", line 274, in check_write_privs
    raise HTTPException(user_info.text, user_info.status_code)
AttributeError: 'Response' object has no attribute 'text'
```

**Comment by maxsibilla** [comment]
With my alternative account I was added the the TMC - The Jackson Laboratory group and was able to register a single dataset and a bulk set of datasets without issue (directories were created)

**Comment by maxsibilla** [comment]
Can not reproduce
