### ISSUE TITLE
Investigate `contains_human_genetic_sequences` error during pipeline processing

### ISSUE THREAD

**Issue by maxsibilla** [sennetconsortium/ingest-api#297]
On production when Brendan initiates a pipeline run of a dataset the following error is occasionally produced:
```
[2024-02-14 20:44:05] ERROR in __init__: 'contains_human_genetic_sequences'
Traceback (most recent call last):
  File "/usr/src/app/src/./routes/entity_CRUD/__init__.py", line 515, in call_airflow
    "full_path": ingest_helper.get_dataset_directory_absolute_path(dataset_request, group_uuid, uuid),
  File "/usr/src/app/src/./routes/entity_CRUD/ingest_file_helper.py", line 32, in get_dataset_directory_absolute_path
    if dataset_record['contains_human_genetic_sequences']:
KeyError: 'contains_human_genetic_sequences'
```

Often I can just reinitialize this without issue but it has been reoccuring.

**Comment by maxsibilla** [comment]
After adding a log line in production and submitting another dataset I can verify that `contains_human_genetic_sequences` is present in the request sent to the Ingest API from the portal:
```
[2024-02-14 21:47:44] INFO in __init__: dataset_request: {
    "assigned_to_group_name": "CODCC",
    "contains_human_genetic_sequences": false,
    "dataset_info": "Curation added empty placeholder microscope_hardware.json file.",
    "dataset_type": "Histology",
    "description": "FFPE, tissue section H&E staining",
    "direct_ancestor_uuids": [
        "23b03073d4385cd3dd15dec5875e3888"
    ],
    "ingest_task": "20240214 CODCC Processing",
    "lab_dataset_id": "JDC_WP_004_c_histology_only_phenocycler",
    "status": "Submitted"
}
```

**Comment by maxsibilla** [comment]
Potential solution is to add a check in `handleProcessing` inside `src/pages/edit/dataset.jsx` to make a check that `contains_human_genetic_sequences` exists inside "values"
