### ISSUE TITLE
Investigate Globus authentication handshake failure

### ISSUE THREAD

**Issue by maxsibilla** [sennetconsortium/ingest-api#610]
Logging into either the Data Sharing Portal or Data Ingest Board on both prod and dev (confirm with @shirey ) resulted in a 500:
```
[2024-12-18 21:39:52] ERROR in app: Exception on /login [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/usr/src/app/src/./routes/auth/__init__.py", line 17, in login
    return _login(current_app.config['GLOBUS_CLIENT_APP_URI'])
  File "/usr/src/app/src/./routes/auth/__init__.py", line 69, in _login
    token_response = confidential_app_auth_client.oauth2_exchange_code_for_tokens(auth_code)
  File "/usr/local/lib/python3.9/site-packages/globus_sdk/auth/client_types/base.py", line 199, in oauth2_exchange_code_for_tokens
    return self.current_oauth2_flow_manager.exchange_code_for_tokens(auth_code)
  File "/usr/local/lib/python3.9/site-packages/globus_sdk/auth/oauth2_authorization_code.py", line 122, in exchange_code_for_tokens
    return self.auth_client.oauth2_token(
  File "/usr/local/lib/python3.9/site-packages/globus_sdk/auth/client_types/base.py", line 356, in oauth2_token
    return self.post(
  File "/usr/local/lib/python3.9/site-packages/globus_sdk/base.py", line 255, in post
    return self._request(
  File "/usr/local/lib/python3.9/site-packages/globus_sdk/base.py", line 496, in _request
    raise self.error_class(r)
globus_sdk.exc.AuthAPIError: (400, 'Error', 'invalid_grant')
```
Example URL:
https://ingest.api.sennetconsortium.org/data-ingest-board-login?code=r6kp3IYWMNH006geTIHXYbTZwmjrtp&state=_default

**Comment by maxsibilla** [comment]
- [ ] Need to add additional logging around the login endpoints to try to capture more specific errors or at least more details regarding Globus endpoints and configurations being used

**Comment by maxsibilla** [comment]
Seems that this fails when issuing a POST to `/v2/oauth2/token` with
```
{
                "grant_type": "authorization_code",
                "code": auth_code.encode("utf-8"),
                "redirect_uri": self.redirect_uri,
}
```
